name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:  # lets you trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: amccnnll
          THEME: 2077
